<?php

namespace App\Http\Controllers;

use App\Models\Inventory;
use App\Models\PropertyInventory;
use App\Models\PropertyRequest;
use App\Models\SupplyRequest;
use Illuminate\Http\Request;

class ScannerController extends Controller
{
    public function index()
    {
        return view('scanner.index');
    }

    public function lookup(Request $request)
    {
        $validated = $request->validate([
            'code' => 'required|string|max:1000',
        ]);
        $code = trim($validated['code']);

        // Support JSON payloads generated by the app: {"type":"INV",...,"sku":"INV-..."}
        $sku = null;
        if (str_starts_with($code, '{')) {
            $payload = json_decode($code, true);
            $sku = is_array($payload) ? ($payload['sku'] ?? null) : null;
        }

        if ($item = Inventory::where('qrcode', $code)
            ->when($sku, fn ($q) => $q->orWhere('sku', $sku))
            ->first()) {
            return response()->json(['redirect' => route('inventory.show', $item->id)]);
        }

        if ($property = PropertyInventory::where('qrcode', $code)
            ->when($sku, fn ($q) => $q->orWhere('barcode', $sku))
            ->first()) {
            return response()->json(['redirect' => route('property.show', $property->id)]);
        }

        // Request QR codes (generated on submit): {"type":"SUPPLY_REQUEST"/"PROPERTY_REQUEST", ...}
        if (is_array($payload) && isset($payload['type'])) {
            if ($payload['type'] === 'SUPPLY_REQUEST'
                && ($req = SupplyRequest::where('qrcode', $code)->orWhere('request_id', $payload['id'] ?? 0)->first())) {
                return response()->json(['redirect' => route('supply-requests.show', $req->request_id)]);
            }
            if ($payload['type'] === 'PROPERTY_REQUEST'
                && ($req = PropertyRequest::where('qrcode', $code)->orWhere('property_id', $payload['id'] ?? 0)->first())) {
                return response()->json(['redirect' => route('property-requests.show', $req->property_id)]);
            }
        }

        // Plain-code fallback on request tables
        if ($req = SupplyRequest::where('qrcode', $code)->first()) {
            return response()->json(['redirect' => route('supply-requests.show', $req->request_id)]);
        }
        if ($req = PropertyRequest::where('qrcode', $code)->first()) {
            return response()->json(['redirect' => route('property-requests.show', $req->property_id)]);
        }

        return response()->json(['message' => 'No item matches this QR code.'], 404);
    }
}
